### ISSUE TITLE
Bit init error

### ISSUE THREAD

**Issue by AlexanderIgnacz** [unwriter/Bitcom#15]
After running `bit init` command, I get following error.

```
/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/insight.js:138
      throw e;
      ^
Invalid Argument
Error
    at new NodeError (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.checkArgument (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)
    at new AddressInfo (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/models/addressinfo.js:20:5)
    at Function.AddressInfo.fromInsight (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/models/addressinfo.js:33:10)
    at Request._callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/insight.js:133:26)
    at Request.self.callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:1076:12) {
  message: 'Invalid Argument',
  stack: 'Invalid Argument\n' +
    'Error\n' +
    '    at new NodeError (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-lib/lib/errors/index.js:20:41)\n' +
    '    at Object.checkArgument (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)\n' +
    '    at new AddressInfo (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/models/addressinfo.js:20:5)\n' +
    '    at Function.AddressInfo.fromInsight (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/models/addressinfo.js:33:10)\n' +
    '    at Request._callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/bitcore-explorers/lib/insight.js:133:26)\n' +
    '    at Request.self.callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at IncomingMessage.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitcom/node_modules/request/request.js:1076:12)'
}
```

**Comment by AlexanderIgnacz** [comment]
Is this library still available library?

**Comment by mathiasrw** [comment]
Long shot: have you tried to use node 10 or 12?

**Comment by AlexanderIgnacz** [comment]
@mathiasrw Yes, it executes same error though I use node 10 or 12.

**Comment by AlexanderIgnacz** [comment]
Currently, I use node 13.
